name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the action on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ensure this matches your project's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # This is where Astro builds the site
        enable_jekyll: false  # Disable Jekyll to avoid issues with files starting with underscores
